package fr.uge.items;

/**
 * Represents an item in the game.
 * An item can be equipped, stacked, sold, rotated, or used in different ways.
 */
public sealed interface Item permits Gold,Magical,Mana,Shield,Sword,RotatableItem,Ration,Malediction,HealingItem  {

	/**
	 * @return the name of the item
	 */
	String name();

	/**
	 * @return the attack value provided by the item
	 */
	int attackValue();

	/**
	 * @return the stamina cost to use the item
	 */
	int staminaCost();

	/**
	 * @return the defense value provided by the item
	 */
	int defendValue();

	/**
	 * @return the width of the item in inventory cells
	 */
	int width();

	/**
	 * @return the height of the item in inventory cells
	 */
	int height();

	/**
	 * @return a new item rotated (width and height swapped)
	 */
	Item rotate();

	/**
	 * @return true if the item is currently rotated
	 */
	boolean isRotated();

	/* ================= Stack management ================= */

	/**
	 * @return true if the item can be stacked
	 */
	default boolean isStackable() {
		return false;
	}

	/**
	 * @return the quantity of items in the stack
	 */
	default int quantity() {
		return 1;
	}

	/**
	 * Adds an amount to the item stack.
	 *
	 * @param amount quantity to add
	 * @return a new item with updated quantity
	 * @throws UnsupportedOperationException if the item is not stackable
	 */
	default Item addQuantity(int amount) {
		throw new UnsupportedOperationException();
	}

	/* ================= Economy ================= */

	/**
	 * @return the price of the item
	 */
	int price();

	/**
	 * @return true if the item can be sold
	 */
	default boolean isSellable() {
		return true;
	}

	/* ================= Regeneration ================= */

	/**
	 * @return stamina regenerated by the item (0 if none)
	 */
	default int staminaRegen() {
		return 0;
	}

	/**
	 * @return health regenerated by the item (0 if none)
	 */
	default int healthRegen() {
		return 0;
	}

	/* ================= Durability ================= */

	/**
	 * @return current durability, or -1 if the item is indestructible
	 */
	default int durability() {
		return -1;
	}

	/**
	 * Decreases the durability of the item.
	 *
	 * @return the item after durability decrease
	 */
	default Item decreaseDurability() {
		return this;
	}

	/**
	 * @return true if the item is broken (durability equals 0)
	 */
	default boolean isBroken() {
		return durability() == 0;
	}

	/* ================= Inventory behavior ================= */

	/**
	 * Checks if the item occupies the given relative cell.
	 *
	 * @param dx horizontal offset
	 * @param dy vertical offset
	 * @return true if the item occupies this cell
	 */
	default boolean occupies(int dx, int dy) {
		return true;
	}

	/* ================= Special properties ================= */

	/**
	 * @return true if the item is cursed
	 */
	default boolean isMalediction() {
		return false;
	}
}
